---
title: "Registered Pets"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  warning = FALSE, 
  message = FALSE
)
```

```{r workspace}
library(tidyverse)
library(DT) # datatable

animals <- read_rds("registered_animals.Rds")

```

This data comes from [The Sunshine Coast Council](https://data.sunshinecoast.qld.gov.au/Administration/Registered-Animals/7f87-i6kx/data # http://rstudio-pubs-static.s3.amazonaws.com/434674_24af082031324d9c8e8739d1ca7227f9.html) in Queensland, Australia (10/1/2020).

A demo analysis can be found [here](http://rstudio-pubs-static.s3.amazonaws.com/434674_24af082031324d9c8e8739d1ca7227f9.html)

### Top 10 Pet Names

```{r datatable}
animals %>% 
  count(gender, species, name, sort = TRUE) %>% 
  group_by(gender, species) %>%
  mutate(Rank = row_number()) %>% 
  ungroup() %>% 
  filter(Rank <= 10) %>% 
  mutate(name = glue::glue("{name} ({n})")) %>% 
  select(-n) %>% 
  pivot_wider(
    names_from = c(gender, species),
    names_sep = "-", 
    names_sort = TRUE,
    values_from = name
  ) %>% 
  DT::datatable(
    filter = "top",
    rownames = FALSE,
    options = list(dom = "i")
  )

```


### Top Breeds of Cats vs Dogs

```{r plot}
p <-
  animals %>% 
  group_by(species) %>% 
  mutate(
    breed = 
      fct_lump_n(breed, 10) %>% 
      fct_infreq() %>% 
      fct_rev()
  ) %>% 
  ungroup() %>% 
  filter(breed != "Other") %>% 
  ggplot(aes(y = breed)) +
  geom_bar(fill = "dodgerblue") +
  facet_wrap(~ species, scales = "free") +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    legend.position = "none"
  ) +
  labs(
    x = "# of Pets",
    y = NULL,
    fill = NULL
  )


plotly::ggplotly(p)



knitr::knit_exit() # stops knitting at this point
```

# more ideas
* gender neutral names
* what names are most popular for unpopular breeds/colors "(other)"
* most popular name by year of birth
* is there a difference in top names for pets that have been spayed/neutered

